### ISSUE TITLE
Add commit codes for deprecation and subsequent removal

### ISSUE THREAD

**Issue by cortadocodes** [octue/conventional-commits#56]
@thclark what do you think about having e.g. `DPR` for deprecation and `REM` for removal of previously deprecated code?

Additionally, should breaking change alerts be attached to releases that:
1. Deprecate code (the code should still work with the same interfaces etc. but the old use will be discouraged)
2. Remove previously deprecated code (the code will no longer work with the old interfaces at all)

**Comment by thclark** [comment]
The breaking change should be applied at the point of code *removal* not code *deprecation*, because that's when the code actually breaks.

Not sure about `DPR` and `REM`...  I quite like the idea that we can pull out an !!!!UPCOMING CHANGES!!!! section if we adopt DPR. But I think I think I'd normally use `REF` or `CHO` (aka "I'm tidying stuff up") for removal of deprecated code... and you could plausibly deprecate one thing as part of an `ENH` or `FEA`.

We could treat it a bit like a BREAKING CHANGE in that if you have DEPRECATION in the commit body it knows what it is? Then we can have a deprecation applied orthogonally to the actual purpose of the commit. In essence we're adding multiple attributes to a commit and we want to be careful not to obfucscate that.

**Comment by cortadocodes** [comment]
Superseded by #57
