### ISSUE TITLE
Add VER: prefix?

### ISSUE THREAD

**Issue by thclark** [octue/conventional-commits#6]
### Use Case

I have a branch with a PR into main, that's failing the semantic version consistency check. So I need to make a commit that changes the version. It's not clear from the existing list what kind of commit that should be.

### Current state

I'm currently using `CHO:`. Perhaps I should be using `OPS:`?

### Suggested solution

Either we add `VER:` to our list, or we explicitly state in the list of purposes for existing ones what we should use for bumping versions.

**Comment by cortadocodes** [comment]
I've been using `OPS` for all version number changes for the current package and `DEP` for all dependency version changes. We could introduce `VER` but it would only be used for this one thing, but maybe that's good? The problem I have with `CHO` is it labels necessary config changes etc as things we don't want to do rather than categorising them according to what they actually do. What do you think?

**Comment by thclark** [comment]
I generally think of ops as devops/Ci stuff but actually this would fall under the same umbrella so I’m happy with that. Can you add it to the description of ‘OPS’ though please?

**Comment by thclark** [comment]
Closing this because we long since decided to use OPS
